### ISSUE TITLE
Input Data Format

### ISSUE THREAD

**Issue by AlfieDiCaprio** [RoyalSkye/AGH#2]
Hi, thank you for your excellent work! After reading the article and the code, I am not very clear about the form of the input data?

The article mentioned "We load the map1 into SUMO [40], by which the distances between gates and the depot are calculated automatically. On top of the map, we first generate AGH instances of 20, 50 and 100 flights which are referred as AGH20, AGH50 and AGH100, respectively.”

As I understand it in the code, the json file is loaded, and the json file contains two dataset files: 1. ID_MAP; 2. CVRPTW. The input data is also divided into SHARED_DATA, UNSHARED_DATA and FILE_MAP.

I really don't understand but I'm curious about the form of the input content. If I wanted to use this code to do a theoretical experiment on a problem such as vrp and use self-generated data as input, the shape of the data would be: (x, y, demand), where (x, y) is the 2D coordinate. Could I directly replace the original input in the original code with the data I generate? I did not find input content such as file_map in the folder.

**Comment by RoyalSkye** [comment]
Hi, sorry for my late reply. I was quite busy with conference rebuttals recently. 
To generate the dataset, you need to run eval_generate_json.py. Then, you will get these files: SHARED_DATA, UNSHARED_DATA, and FILE_MAP. An example of the data format can be found [here](https://github.com/RoyalSkye/AGH/blob/main/Improvement_based/cplex/eval_generate_json.py#L42). You can also check the data format by "reading" these generated files.
It may not be easy to adapt to VRP directly, since the improvement-based code is not clean. I would suggest trying the construction-based one or other repo leveraging the LNS framework, such as [NLNS](https://github.com/ahottung/NLNS).

**Comment by AlfieDiCaprio** [comment]
Thank you for your time, I'll try to complete it.

I'm grateful for your reply, and hope the program chair will eventually accept your paper. 

Best wishes.
